#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N lab1_3d
#PBS -o lab1_3d.out
#PBS -e lab1_3d.err
#PBS -q workq
#PBS -A loni_cyen405
module load matlab/r2017a
MATLAB_FILE="lab1_3d"
matlab -logfile ./lab1_dc.txt -nodisplay -r $MATLAB_FILE
